project:
  type: website
  output-dir: docs

website:
  title: "Fleming Lab"
  navbar:
    left:
      - OurTeam.qmd
      - Research.qmd
      - Publications.qmd
      - Contact.qmd

format:
  html:
    theme:
      - flatly
    css: styles.css
    toc: false

editor: visual

