---
title: "Our Research"
---

*Page under construction, please check back later*


## Salmonid Ecology and Evolution 

### Atlantic Salmon

Atlantic salmon are socially, ecologically, and economically important throughout their range. We are interested in both fundamental questions in Atlantic salmon evolution and ecology as well as applied conservation research. We are investigating topics such as the interactions between Ouananiche (landlocked) and anadromous salmon in Newfoundland, impacts of aquaculture escapes on wild populations, factors that impact at-sea survival, and the extent of local adaptation to climate. 

### Brown Trout in Newfoundland

Brown trout were introduced to Canada from Europe in the late 19th century. We investigate interactions between brown trout and Atlantic salmon in Newfoundland, and are looking at the survival and spread of different genetic lines. 

### Arctic Charr in Labrador

As part of the Ocean Frontier Institute's Sustainable Nunatsiavut Futures project, we are studying the diet and growth patterns of Arctic Charr in Labrador. 


